


select * from BOOK

CREATE TABLE RIVIEW(
	REVIEWID INT PRIMARY KEY IDENTITY(15,4),
	USERID INT FOREIGN KEY REFERENCES [USER] (USERID)
	ON DELETE CASCADE
       ON UPDATE CASCADE
	
)

CREATE TABLE RATING(
	RATINGID INT PRIMARY KEY IDENTITY(16,5),
	RATING INT ,
	USERID INT FOREIGN KEY REFERENCES [USER] (USERID),
	BOOKID INT FOREIGN KEY REFERENCES [BOOK] (BOOKID)
	
	ON DELETE CASCADE
       ON UPDATE CASCADE
	   
)
SELECT * FROM RATING

CREATE TABLE [LIKE](
	LIKEID INT PRIMARY KEY IDENTITY(17,6),
	USERID INT FOREIGN KEY REFERENCES [USER] (USERID),
	BOOKID INT FOREIGN KEY REFERENCES [BOOK] (BOOKID)
	ON DELETE CASCADE
       ON UPDATE CASCADE
)


CREATE TABLE [VIEW](
	VIEWID INT PRIMARY KEY IDENTITY(17,6),
	USERID INT FOREIGN KEY REFERENCES [USER] (USERID),
	BOOKID INT FOREIGN KEY REFERENCES [BOOK] (BOOKID)
	ON DELETE CASCADE
       ON UPDATE CASCADE
)

