USE [master]

GO
/****** Object:  Database [OLS]    Script Date: 12/08/2019 1:17:11 PM ******/
CREATE DATABASE [OLS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'OLS', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\OLS.mdf' , SIZE = 3264KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'OLS_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\OLS_log.ldf' , SIZE = 832KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [OLS] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [OLS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [OLS] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [OLS] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [OLS] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [OLS] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [OLS] SET ARITHABORT OFF 
GO
ALTER DATABASE [OLS] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [OLS] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [OLS] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [OLS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [OLS] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [OLS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [OLS] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [OLS] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [OLS] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [OLS] SET  ENABLE_BROKER 
GO
ALTER DATABASE [OLS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [OLS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [OLS] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [OLS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [OLS] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [OLS] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [OLS] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [OLS] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [OLS] SET  MULTI_USER 
GO
ALTER DATABASE [OLS] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [OLS] SET DB_CHAINING OFF 
GO
ALTER DATABASE [OLS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [OLS] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [OLS] SET DELAYED_DURABILITY = DISABLED 
GO
USE [OLS]
GO
/****** Object:  Table [dbo].[AUTHOR]    Script Date: 12/08/2019 1:17:12 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[AUTHOR](
	[AUTHORID] [int] IDENTITY(8124566,789) NOT NULL,
	[FIRSTNAME] [varchar](12) NULL,
	[LASTNAME] [varchar](12) NULL,
	[MIDDLENAME] [varchar](12) NULL,
	[BIOGRAPHY] [varchar](1000) NULL,
	[ALIASNAME] [varchar](8) NULL,
	[THUMBNAIL_PATH] [varchar](70) NULL,
PRIMARY KEY CLUSTERED 
(
	[AUTHORID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[BOOK]    Script Date: 12/08/2019 1:17:12 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[BOOK](
	[BOOKID] [int] IDENTITY(233121,78) NOT NULL,
	[ISBN_NUMBER] [bigint] NOT NULL,
	[NAME] [varchar](30) NULL,
	[STATUS] [varchar](10) NULL,
	[SYNOPOSIS] [varchar](300) NOT NULL,
	[ISPUBLISHED] [bit] NULL,
	[REFERENCE] [varchar](100) NULL,
	[DATE_PUBLISHED] [datetime] NULL,
	[CREATED_DATE] [datetime] NULL,
	[PRICE] [float] NULL,
	[PERCENTAGE_OFF] [int] NULL,
	[GENREID] [int] NULL,
	[STAFFID] [int] NULL,
	[PRODUCERID] [int] NULL,
	[TRANSLATEDFROM] [int] NULL,
	[LANGUAGEID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[BOOKID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[BOOK_AUTHOR]    Script Date: 12/08/2019 1:17:12 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BOOK_AUTHOR](
	[BOOK_AUTHORID] [int] IDENTITY(9,9) NOT NULL,
	[BOOKID] [int] NULL,
	[AUTHORID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[BOOK_AUTHORID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[BOOK_CATEGORY]    Script Date: 12/08/2019 1:17:12 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BOOK_CATEGORY](
	[BOOK_CATEGORYID] [int] IDENTITY(9,9) NOT NULL,
	[BOOKID] [int] NULL,
	[CATEGORYID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[BOOK_CATEGORYID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[BOOK_IMAGE]    Script Date: 12/08/2019 1:17:12 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[BOOK_IMAGE](
	[BOOK_IMAGEID] [int] IDENTITY(5,6) NOT NULL,
	[BOOKID] [int] NULL,
	[IMAGEPATH] [varchar](150) NULL,
PRIMARY KEY CLUSTERED 
(
	[BOOK_IMAGEID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[BOOK_SOFTCOPY]    Script Date: 12/08/2019 1:17:12 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[BOOK_SOFTCOPY](
	[BSCID] [int] IDENTITY(12,13) NOT NULL,
	[BOOKID] [int] NULL,
	[VERSION] [varchar](10) NULL,
	[FILEPATH] [varchar](80) NOT NULL,
	[FILESIZE] [float] NULL,
PRIMARY KEY CLUSTERED 
(
	[BSCID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[CATEGORY]    Script Date: 12/08/2019 1:17:12 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CATEGORY](
	[CATEGORYID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [varchar](12) NOT NULL,
	[DESCRIPTION] [varchar](200) NULL,
	[REFERENCE_KEY] [varchar](20) NOT NULL,
	[CATEGORY_THUMBNAIL] [varchar](80) NULL,
PRIMARY KEY CLUSTERED 
(
	[CATEGORYID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[GENRE]    Script Date: 12/08/2019 1:17:12 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[GENRE](
	[GENREID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [varchar](12) NOT NULL,
	[DESCRIPTION] [varchar](200) NULL,
	[REFERENCE_KEY] [varchar](20) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[GENREID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[LANGUAGE]    Script Date: 12/08/2019 1:17:12 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[LANGUAGE](
	[LANGUAGEID] [int] IDENTITY(5,67) NOT NULL,
	[LANGUAGE] [varchar](20) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[LANGUAGEID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[PRODUCER]    Script Date: 12/08/2019 1:17:12 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PRODUCER](
	[PRODUCERID] [int] IDENTITY(34,7) NOT NULL,
	[NAME] [varchar](50) NULL,
	[ADDRESS] [varchar](100) NULL,
	[CONTACT] [varchar](50) NULL,
	[EMAIL] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[PRODUCERID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[ROLE]    Script Date: 12/08/2019 1:17:12 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ROLE](
	[ROLEID] [int] IDENTITY(3,3) NOT NULL,
	[ROLE] [varchar](10) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ROLEID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[USER]    Script Date: 12/08/2019 1:17:12 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[USER](
	[USERID] [int] IDENTITY(67898,90) NOT NULL,
	[USERNAME] [varchar](14) NOT NULL,
	[PASSWORDHASH] [varchar](70) NOT NULL,
	[FIRSTNAME] [varchar](20) NULL,
	[LASTNAME] [varchar](20) NULL,
	[MIDDLENAME] [varchar](20) NULL,
	[THUMBNAIL_PATH] [varchar](70) NULL,
	[EMAIL] [varchar](20) NOT NULL,
	[ROLEID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[USERID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[WATCHLIST]    Script Date: 12/08/2019 1:17:12 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[WATCHLIST](
	[WATCHLISTID] [int] IDENTITY(12,3) NOT NULL,
	[BOOKID] [int] NULL,
	[USERID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[WATCHLISTID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET IDENTITY_INSERT [dbo].[AUTHOR] ON 

INSERT [dbo].[AUTHOR] ([AUTHORID], [FIRSTNAME], [LASTNAME], [MIDDLENAME], [BIOGRAPHY], [ALIASNAME], [THUMBNAIL_PATH]) VALUES (8126933, N'Jeremy', N'Sam', N'K', N'Lorem ipsum dolor sit amet, velit efficiantur theophrastus vim ad, et mea adhuc officiis. Verear option menandri ut pro. Quo eu suas illum nominavi. In nam alii nostro, diceret copiosae patrioque ut usu. No ridens vivendo vel. Lorem ipsum dolor sit amet, velit efficiantur theophrastus vim ad, et mea adhuc officiis. Verear option menandri ut pro. Quo eu suas illum nominavi. In nam alii nostro, diceret copiosae patrioque ut usu. No ridens vivendo vel.   ', N'J.S.K', N'/UserImages/DfSlWMhRBg.jpg')
INSERT [dbo].[AUTHOR] ([AUTHORID], [FIRSTNAME], [LASTNAME], [MIDDLENAME], [BIOGRAPHY], [ALIASNAME], [THUMBNAIL_PATH]) VALUES (8127722, N'Scalet', N'Witch', N'Wanda', N'  Lorem ipsum dolor sit amet, velit efficiantur theophrastus vim ad, et mea adhuc officiis. Verear option menandri ut pro. Quo eu suas illum nominavi. In nam alii nostro, diceret copiosae patrioque ut usu. No ridens vivendo vel. Lorem ipsum dolor sit amet, velit efficiantur theophrastus vim ad, et mea adhuc officiis. Verear option menandri ut pro. Quo eu suas illum nominavi. In nam alii nostro, diceret copiosae patrioque ut usu. No ridens vivendo vel.   ', N'SWW', N'/UserImages/6aYxEDtoRP.jpg')
SET IDENTITY_INSERT [dbo].[AUTHOR] OFF
SET IDENTITY_INSERT [dbo].[CATEGORY] ON 

INSERT [dbo].[CATEGORY] ([CATEGORYID], [NAME], [DESCRIPTION], [REFERENCE_KEY], [CATEGORY_THUMBNAIL]) VALUES (1, N'Sci Fic', N'Science fiction book e.g DC. Comic (Dr. Strange)', N'Sci Fic', NULL)
INSERT [dbo].[CATEGORY] ([CATEGORYID], [NAME], [DESCRIPTION], [REFERENCE_KEY], [CATEGORY_THUMBNAIL]) VALUES (2, N'Adventure', N'Adventure Adventure Adventure Adventure', N'Adventure', NULL)
SET IDENTITY_INSERT [dbo].[CATEGORY] OFF
SET IDENTITY_INSERT [dbo].[GENRE] ON 

INSERT [dbo].[GENRE] ([GENREID], [NAME], [DESCRIPTION], [REFERENCE_KEY]) VALUES (1, N'Music', N'Music music music', N'Musi')
SET IDENTITY_INSERT [dbo].[GENRE] OFF
SET IDENTITY_INSERT [dbo].[LANGUAGE] ON 

INSERT [dbo].[LANGUAGE] ([LANGUAGEID], [LANGUAGE]) VALUES (5, N'English')
INSERT [dbo].[LANGUAGE] ([LANGUAGEID], [LANGUAGE]) VALUES (72, N'Yoruba')
INSERT [dbo].[LANGUAGE] ([LANGUAGEID], [LANGUAGE]) VALUES (139, N'Vietnamese')
INSERT [dbo].[LANGUAGE] ([LANGUAGEID], [LANGUAGE]) VALUES (206, N'Igbo')
INSERT [dbo].[LANGUAGE] ([LANGUAGEID], [LANGUAGE]) VALUES (273, N'Hausa')
SET IDENTITY_INSERT [dbo].[LANGUAGE] OFF
SET IDENTITY_INSERT [dbo].[PRODUCER] ON 

INSERT [dbo].[PRODUCER] ([PRODUCERID], [NAME], [ADDRESS], [CONTACT], [EMAIL]) VALUES (48, N'Peter Jackson', N'Pukerua Bay, New Zealand', N'+84(0)1697979138', N'peterjackson@gmail.com')
SET IDENTITY_INSERT [dbo].[PRODUCER] OFF
SET IDENTITY_INSERT [dbo].[ROLE] ON 

INSERT [dbo].[ROLE] ([ROLEID], [ROLE]) VALUES (3, N'Admin')
INSERT [dbo].[ROLE] ([ROLEID], [ROLE]) VALUES (6, N'Customer')
INSERT [dbo].[ROLE] ([ROLEID], [ROLE]) VALUES (9, N'Staff')
INSERT [dbo].[ROLE] ([ROLEID], [ROLE]) VALUES (12, N'Admin')
INSERT [dbo].[ROLE] ([ROLEID], [ROLE]) VALUES (15, N'Customer')
INSERT [dbo].[ROLE] ([ROLEID], [ROLE]) VALUES (18, N'Staff')
SET IDENTITY_INSERT [dbo].[ROLE] OFF
SET IDENTITY_INSERT [dbo].[USER] ON 

INSERT [dbo].[USER] ([USERID], [USERNAME], [PASSWORDHASH], [FIRSTNAME], [LASTNAME], [MIDDLENAME], [THUMBNAIL_PATH], [EMAIL], [ROLEID]) VALUES (68078, N'Admin', N'e3afed0047b08059d0fada10f400c1e5', N'Admin', N'Admin', N'Admin', N'/UserImages/NBJqkFmYxD.JPG', N'admin@ad.vn', 3)
SET IDENTITY_INSERT [dbo].[USER] OFF
SET ANSI_PADDING ON

GO
/****** Object:  Index [UQ__AUTHOR__173B5954EA6E7762]    Script Date: 12/08/2019 1:17:12 PM ******/
ALTER TABLE [dbo].[AUTHOR] ADD UNIQUE NONCLUSTERED 
(
	[ALIASNAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
/****** Object:  Index [UQ__CATEGORY__78E94B6FC864D4EF]    Script Date: 12/08/2019 1:17:12 PM ******/
ALTER TABLE [dbo].[CATEGORY] ADD UNIQUE NONCLUSTERED 
(
	[REFERENCE_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
/****** Object:  Index [UQ__GENRE__78E94B6F47B3A157]    Script Date: 12/08/2019 1:17:12 PM ******/
ALTER TABLE [dbo].[GENRE] ADD UNIQUE NONCLUSTERED 
(
	[REFERENCE_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BOOK] ADD  DEFAULT ((0)) FOR [ISPUBLISHED]
GO
ALTER TABLE [dbo].[BOOK] ADD  DEFAULT (getdate()) FOR [CREATED_DATE]
GO
ALTER TABLE [dbo].[BOOK]  WITH CHECK ADD FOREIGN KEY([GENREID])
REFERENCES [dbo].[GENRE] ([GENREID])
GO
ALTER TABLE [dbo].[BOOK]  WITH CHECK ADD FOREIGN KEY([LANGUAGEID])
REFERENCES [dbo].[LANGUAGE] ([LANGUAGEID])
GO
ALTER TABLE [dbo].[BOOK]  WITH CHECK ADD FOREIGN KEY([PRODUCERID])
REFERENCES [dbo].[PRODUCER] ([PRODUCERID])
GO
ALTER TABLE [dbo].[BOOK]  WITH CHECK ADD FOREIGN KEY([STAFFID])
REFERENCES [dbo].[USER] ([USERID])
GO
ALTER TABLE [dbo].[BOOK]  WITH CHECK ADD FOREIGN KEY([TRANSLATEDFROM])
REFERENCES [dbo].[BOOK] ([BOOKID])
GO
ALTER TABLE [dbo].[BOOK_AUTHOR]  WITH CHECK ADD FOREIGN KEY([AUTHORID])
REFERENCES [dbo].[AUTHOR] ([AUTHORID])
GO
ALTER TABLE [dbo].[BOOK_AUTHOR]  WITH CHECK ADD FOREIGN KEY([BOOKID])
REFERENCES [dbo].[BOOK] ([BOOKID])
GO
ALTER TABLE [dbo].[BOOK_CATEGORY]  WITH CHECK ADD FOREIGN KEY([BOOKID])
REFERENCES [dbo].[BOOK] ([BOOKID])
GO
ALTER TABLE [dbo].[BOOK_CATEGORY]  WITH CHECK ADD FOREIGN KEY([CATEGORYID])
REFERENCES [dbo].[CATEGORY] ([CATEGORYID])
GO
ALTER TABLE [dbo].[BOOK_IMAGE]  WITH CHECK ADD FOREIGN KEY([BOOKID])
REFERENCES [dbo].[BOOK] ([BOOKID])
GO
ALTER TABLE [dbo].[BOOK_SOFTCOPY]  WITH CHECK ADD FOREIGN KEY([BOOKID])
REFERENCES [dbo].[BOOK] ([BOOKID])
GO
ALTER TABLE [dbo].[USER]  WITH CHECK ADD FOREIGN KEY([ROLEID])
REFERENCES [dbo].[ROLE] ([ROLEID])
GO
ALTER TABLE [dbo].[WATCHLIST]  WITH CHECK ADD FOREIGN KEY([BOOKID])
REFERENCES [dbo].[BOOK] ([BOOKID])
GO
ALTER TABLE [dbo].[WATCHLIST]  WITH CHECK ADD FOREIGN KEY([USERID])
REFERENCES [dbo].[USER] ([USERID])
GO
USE [master]
GO
ALTER DATABASE [OLS] SET  READ_WRITE 
GO
